# name: Azure Container Apps Deploy - Frontend

# on:
#   workflow_run:
#     workflows: ["Frontend Docker Build"]
#     types:
#       - completed

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}-frontend
#   CONTAINER_APP_NAME: frontend-ca

# jobs:
#     deploy:
#         runs-on: ubuntu-latest

#         steps:

#             - name: Checkout
#               uses: actions/checkout@v4

#             - name: Log in to Azure
#               uses: azure/login@v1
#               with:
#                 creds: ${{ secrets.AZURE_CREDENTIALS }}

#             - name: Extract metadata (tags, labels) for Docker
#               id: meta
#               uses: docker/metadata-action@v5
#               with:
#                 images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

#             - name: Deploy to Azure Container Apps
#               uses: azure/container-apps-deploy-action@v1
#               with:
#                 imageToDeploy: ghcr.io/adamhockemeyer/ai-showcase-frontend${{ steps.meta.outputs.tags[0] }}
#                 resourceGroup: ${{ needs.bicep_deploy.outputs.resourceGroup }}
#                 containerAppEnvironment: ${{ needs.bicep_deploy.outputs.containerAppEnvironment }}
#                 containerAppName: '${{ env.CONTAINER_APP_NAME }}-${{ steps.meta.outputs.tags[0] }}'
                