name: Bicep Build

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
    workflow_dispatch:

defaults:
    run:
        working-directory: ./infra/bicep

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            #Create this Azure resource group if it doesn't exist
            RESOURCE_GROUP_NAME: ai-showcase-rg
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }} # Attempts to check out the head ref if it exists (for PRs)

            - name: Set up Azure CLI
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Bicep Build
              run: |
                    az bicep build --file main.bicep
            
            - name: Commit main.json
              working-directory: ${{ github.workspace }}
              run: |
                if [ -z "$(git status --porcelain)" ]; then
                        echo "No changes to commit."
                    else
                        git checkout -b temp-branch || git checkout ${{ github.ref }} # Checkout a new branch or the current ref
                        git add main.json
                        git commit -m "Add generated main.json from Bicep build"
                        git push origin HEAD:${{ github.head_ref }} -f # Force push to the head ref, adjust as necessary
                    fi

            - name: Bicep What-if
              id: bicep
              run: |
                    az deployment group what-if --resource-group ai-showcase-rg --template-file main.bicep --name ai-showcase

            - name: Comment PR
              if: github.event_name == 'pull_request'
              uses: actions/github-script@v7
              env:
                PLAN: "bicep\n${{ steps.bicep.outputs.stdout }}"
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    // 1. Retrieve existing bot comments for the PR
                    const { data: comments } = await github.rest.issues.listComments({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                    })
                    const botComment = comments.find(comment => {
                        return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
                    })

                    // 2. Prepare format of the comment
                    const output = `#### Az Deployment What-If 📖\`${{ steps.bicep.outcome }}\`

                    <details><summary>Show Plan</summary>

                    \`\`\`\n
                    ${process.env.PLAN}
                    \`\`\`

                    </details>

                    *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;

                    // 3. If we have a comment, update it, otherwise create a new one
                    if (botComment) {
                        github.rest.issues.updateComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        comment_id: botComment.id,
                        body: output
                        })
                    } else {
                        github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: output
                        })
                    }