name: Terraform Plan

on:
    push:
        branches:
            - main
    workflow_dispatch:

defaults:
    run:
        working-directory: ./infra/terraform

jobs:
    terraform:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
               creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Format
              id: fmt
              run: terraform fmt -check -no-color
              continue-on-error: true

            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            - name: Terraform Plan
              id: plan
              run: |
                terraform plan -no-color
              continue-on-error: true

            - name: Terraform Apply
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              id: apply
              run: terraform apply -auto-approve -no-color
              continue-on-error: true

              